### ISSUE TITLE
App Crashes on "Logout of Dropbox"

### ISSUE THREAD

**Issue by mcguiresm** [todotxt/todo.txt-ios#101]
Using most recent TestFlight build app still crashes on "Logout of Dropbox"
Steps to reproduce:
1.) Open Todo.txt
2.) Login to Dropbox
3.) Hit home button
4.) Double tap home button, long press app and tap to close Todo.txt
5.) Re-open Todo.txt
6.) Goto settings and tap "Logout of Dropbox"
7.) Crash

This is on iOS 5 iPhone 4S with Todo.txt Touch 1.0#13

**Comment by ginatrapani** [comment]
Uninstall Todo.txt Touch entirely. Then try to repro. For me, it
doesn't happen. Not sure why.

On Wed, Dec 21, 2011 at 4:06 AM, Shawn McGuire
reply@reply.github.com
wrote:

> Using most recent TestFlight build app still crashes on "Logout of Dropbox"
> Steps to reproduce:
> 1.) Open Todo.txt
> 2.) Login to Dropbox
> 3.) Hit home button
> 4.) Double tap home button, long press app and tap to close
> 5.) Re-open Todo.txt
> 6.) Goto settings and tap "Logout of Dropbox"
> 7.) Crash
> 
> This is on iOS 5 iPhone 4S with Todo.txt Touch 1.0 #13
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/101

## 

http://ginatrapani.org
http://twitter.com/ginatrapani

**Comment by mcguiresm** [comment]
You are correct, it seems that if it is not uninstalled prior to running install from the TestFlight email the bug carries over.  Thanks @ginatrapani
