### ISSUE TITLE
Add a badge count of undone tasks to the app icon

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#102]
Either the total count of undone tasks, or the total count of prioritized, or prioritized a certain level tasks.

**Comment by paulroub** [comment]
Would the criteria be a setting, or inferred from "undone tasks matching the most-recently-used filter"?  Actually, this is where I'd love to see the CLI's due date plugin ("t:2012-01-01") internalized in the mobile app. Undone-but-not-due tasks in the count may be irritating.

**Comment by ginatrapani** [comment]
I imagined it would be a dropdown setting where you choose 1 of 4
options: no badge count at all, total item count, just prioritized
tasks, just tasks prioritized A. Does that seem sensible?

On Thu, Dec 29, 2011 at 2:16 AM, Paul Roub
reply@reply.github.com
wrote:

> Would the criteria be a setting, or inferred from "undone tasks matching the most-recently-used filter"?  Actually, this is where I'd love to see the CLI's due date plugin ("t:2012-01-01") internalized in the mobile app. Undone-but-not-due tasks in the count may be irritating.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/102#issuecomment-3297435

## 

http://ginatrapani.org
http://twitter.com/ginatrapani

**Comment by paulroub** [comment]
Makes sense. And for people like me using the post-dating plugin, limiting to prioritized tasks should solve the problem - who prioritizes future tasks?
