### ISSUE TITLE
WebDAV sync support?

### ISSUE THREAD

**Issue by avamk** [todotxt/todo.txt-ios#117]
Hello,

As far as I can tell, todo.txt-touch currently only supports syncing todo lists via DropBox. Is it possible to implement syncing via a generic WebDAV share as well? This way, todo.txt won't be tied to any particular proprietary service.

Thanks!

**Comment by ginatrapani** [comment]
WebDAV is an interesting suggestion. Let's discuss on the mailing list:
http://groups.yahoo.com/group/todotxt/

On Sat, Feb 4, 2012 at 10:01 AM, avamk
reply@reply.github.com
wrote:

> Hello,
> 
> As far as I can tell, todo.txt-touch currently only supports syncing todo lists via DropBox. Is it possible to implement syncing via a generic WebDAV share as well? This way, todo.txt won't be tied to any particular proprietary service.
> 
> Thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/117

## 

http://ginatrapani.org

**Comment by neuhaus** [comment]
I second this request. Since the summer of snowden, who _doesn't_ want to use his own, private online storage instead of services like Dropbox?

However, I found this FAQ entry http://blog.todotxt.com/post/83519225401/faq-support-for-cloud-providers-other-than-dropbox
so I guess I have to look for another todolist app for iOS that does offer WebDAV support. Bummer.

**Comment by mikeryan** [comment]
Thirding this request. I have extensive private infrastructure and WebDav is the least common denominator. I would pay money for this feature!

**Comment by grahamc** [comment]
Would you pay in dev time?

**Comment by mikeryan** [comment]
Unfortunately I have an excess of money but no time to spare.

**Comment by neuhaus** [comment]
If we had a system like [BitHub](https://github.com/WhisperSystems/BitHub) or [Bountysource](https://www.bountysource.com/), you could pay someone to implement it.

**Comment by kollaesch** [comment]
Hi there,
I was thinking/looking also for WebDAV-support. This would finally bring todo.txt to my Synology Diskstation. I browsed github and found this... _https://github.com/leyleo/leowebdav_

Would this suffice as a library for WebDAV?
