### ISSUE TITLE
Swipe left to delete a task

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#121]
Swipe to complete is one of this app's best features. Let's also add swipe to delete. 

If user swipes right across task, the button that appears will be Complete (as it is now). If user swipes left across a task, display a Delete button which deletes a task when tapped.

**Comment by cprichard** [comment]
I like.

**Comment by mcguiresm** [comment]
I am currently working on this

**Comment by mcguiresm** [comment]
Thoughts on doing some thing like this http://idevrecipes.com/2011/04/14/how-does-the-twitter-iphone-app-implement-side-swiping-on-a-table/ ?
Then someone can just swipe and choose to either choose to mark complete/incomplete, delete, or archive, etc.

**Comment by cprichard** [comment]
Looks like an excellent, extensible solution. Go for it!

**Comment by ginatrapani** [comment]
Yup, I like it. Let's try it.

On Tuesday, March 13, 2012, Craig Prichard <
reply@reply.github.com>
wrote:

> Looks like an excellent, extensible solution. Go for it!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/121#issuecomment-4472345

## 

http://ginatrapani.org

**Comment by ginatrapani** [comment]
Superseded by #172
