### ISSUE TITLE
Duplicate Projects in Tasks

### ISSUE THREAD

**Issue by punkzter** [todotxt/todo.txt-ios#123]
I am using the latest version of ToDo.txt for the Android OS.  

I have a filter set for two project types (+Life and +Trip).  When I add a new task, and give it a project (+Life), and then go to update that task, it duplicates the project type in the text.  I.e. the task looks like:  (A) Eat +Life +Life

Thanks,
Brad

**Comment by paulroub** [comment]
I think you meant to add this issue to the todo.txt-touch project.  There's a fix (not yet merged into the app) coming, see ginatrapani/todo.txt-touch#256

**Comment by ginatrapani** [comment]
Yes, that fix will get merged today. Sorry for your trouble, closing this issue now.
