### ISSUE TITLE
Long todo items don't scroll while editing.

### ISSUE THREAD

**Issue by jopod** [todotxt/todo.txt-ios#124]
A long todo item running below the keypad does not allow scrolling to view the text as it is entered or edited. I ran into this bug today on an iPhone and didn't spend any time doing more testing.

**Comment by chuckbjones** [comment]
Maybe [this](https://github.com/HansPinckaers/GrowingTextView) will help

**Comment by jopod** [comment]
I started looking into this bug but didn't find it. The problem is somewhere in the rather (overly?) complicated TaskEditViewController or one of it's underlings like SSTextView. I went down the rabbit hole of TaskEditAccessoryView but didn't find a real problem. I tried a few things but I'm not happy with the results yet. The best result I could get so far was to manually adjust the textView.frame origin and height. If I find time I'll take another look at it.

**Comment by marsepu** [comment]
the textView height is set to 416 and it is layer out behind the accessoryView and Keyboard. the solution is to set the height to something like 156.
