### ISSUE TITLE
"Toast" notifications

### ISSUE THREAD

**Issue by chuckbjones** [todotxt/todo.txt-ios#128]
[This library](https://github.com/scottjacksonx/SJNotificationViewController) may work for adding toast-like notification messages like the android app does (e.g. when automatically going into offline mode)

**Comment by chuckbjones** [comment]
Or [this one](https://github.com/onemightyroar/YRDropdownView)

**Comment by ginatrapani** [comment]
That looks very nice, I like.

On Tue, Mar 13, 2012 at 1:06 AM, Charles Jones
reply@reply.github.com
wrote:

> [This library](https://github.com/scottjacksonx/SJNotificationViewController) may work for adding toast-like notification messages like the android app does (e.g. when automatically going into offline mode)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/128

## 

http://ginatrapani.org
