### ISSUE TITLE
On initial install, icon badge counts show when Setting is none

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#133]
Related mailing list thread:

http://tech.groups.yahoo.com/group/todotxt/message/4152

**Comment by chuckbjones** [comment]
Probably need to set the default value of "badgeCount_preference" to "none" in didFinishLaunchingWithOptions.

**Comment by chuckbjones** [comment]
@marsepu, can you submit a pull request for this, so that it can be included in the next release?

**Comment by ginatrapani** [comment]
Weird, I didn't receive the pull request for this, only the one for project/context capitalization. I can pull in the patch anyway. Thanks.

**Comment by chuckbjones** [comment]
@ginatrapani Is this still an issue? It doesn't look like the fix was ever applied.

**Comment by ginatrapani** [comment]
I applied the fix locally and it didn't fix the issue.

**Comment by chuckbjones** [comment]
Hmm, it worked for me ;) PR on its way.
