### ISSUE TITLE
Add '+' and '@' to base keyboard

### ISSUE THREAD

**Issue by andb** [todotxt/todo.txt-ios#135]
Im not sure what can be done with IOS apps and their keyboards...

It would be great if I didnt have to drill down 2 levels to get to the '+' and '@' keys. 

I can think of two ways to possibly make an easier experience to enter new context projects. Either would be enough, both together might be even better:
-  a more narrow spacebar and add these two keys to the right of it
- after pressing project or context buttons, allow text to be entered, filtering as the user types, add new if no match is found

Or is there a simple way to avoid having to press '?123' then '#+=' each time I want a new context / project? Even the selector widget without autofilter is going to be tough to use once I have a few tens of these, I'm concerned...

Thanks for considering this issue, and let me know if there is already a good way to do this that im missing.

(I also have your android app, its only 1 click deep and I mostly only read on that device, so I'm quite happy with that UX)

**Comment by andb** [comment]
I just found the ticket #126, this is largely a duplicate of that, I overlooked that ticket due to its focus on the date as context.

Feel free to close this ticket and move my comment to #126 if you feel its appropriate.

**Comment by chuckbjones** [comment]
See #41 for why the standard keyboard was chosen, but yes the context/project pickers need to be redesigned. #116 seems like a good idea.
