### ISSUE TITLE
Manual sync not Downloading

### ISSUE THREAD

**Issue by hungrymedia** [todotxt/todo.txt-ios#137]
Upon opening iOS app, Todo.txt Touch prompts for manual sync since the device's data and Dropbox's data are out of sync.

After choosing Download to device from the Manual Sync dialogue, I am seeing brief activity in the iPhone's top info bar, but the device never updates with the data from Dropbox.

I have tried "force quitting" the app on the device, but reopening and initiating a sync yields the same results.

**Comment by ginatrapani** [comment]
In settings, do you have Work Offline on?

**Comment by hungrymedia** [comment]
Yes. Work Offline is turned on. This may have been a dropbox hiccup as it cleared up the next day and has worked since. 

Apologies for not updating this issue.

**Comment by ginatrapani** [comment]
Glad to hear that, thanks for closing the issue.
