### ISSUE TITLE
Allow priority to use numbers instead of alphabet

### ISSUE THREAD

**Issue by andb** [todotxt/todo.txt-ios#138]
I would like to be able to use numbers to set priorities instead of letters. I would suggest to actually support a decimal value, which could open a lot of possibilities for personal customization as far as sorting is concerned.

Viewing tasks with already set priority works fine - they are already ordered. But when you want to set a new item with a priority system over 5-10 letters it can be difficult to know what priority to use. The core of the problem is that the alphabet is learned as a set of symbols with individual meaning, not with a relationship to each other. Numbers are learned as points on a continuum, which makes it far easier to understand and set relative priority for tasks.

Thanks for considering this feature request.

**Comment by ginatrapani** [comment]
Why not just use the line numbers?

This would be a major change to the todo.txt format, so let's discus on the mailing list with the community. Please post this message there. Thank you!

http://tech.groups.yahoo.com/group/todotxt/
