### ISSUE TITLE
App keeps turning on "Work Offline"

### ISSUE THREAD

**Issue by ghost** [todotxt/todo.txt-ios#140]
Hi everyone,

there's an issue with the iOS version that's really annoying...the app keeps switching to "Work Offline" mode, although I keep turning the switch off (i.e. work online). Very often I notice on my laptop that the todo.txt is missing some tasks. Then I check the app and notice that it has (again) set itself to "work offline". Why does it keep doing that? And how can I prevent this?

Thank you for any help!
Martin

**Comment by ginatrapani** [comment]
Ugh, yes, the work offline feature needs improvement. Let's discuss on
the community mailing list so everyone can participate (I'm the only
one who gets issue tracker notifications):

http://tech.groups.yahoo.com/group/todotxt/

On Wed, Jul 18, 2012 at 3:24 AM, basteln
reply@reply.github.com
wrote:

> Hi everyone,
> 
> there's an issue with the iOS version that's really annoying...the app keeps switching to "Work Offline" mode, although I keep turning the switch off (i.e. work online). Very often I notice on my laptop that the todo.txt is missing some tasks. Then I check the app and notice that it has (again) set itself to "work offline". Why does it keep doing that? And how can I prevent this?
> 
> Thank you for any help!
> Martin
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/140

## 

http://ginatrapani.org

**Comment by chuckbjones** [comment]
I'm going to start porting over @eisbehr's 'manual sync' logic from the [Android app](https://github.com/ginatrapani/todo.txt-touch/pull/277). This will probably involve implementing #128 as well.

**Comment by ginatrapani** [comment]
Fantastic, thank you! Let me know how I can help. Woohoo!
