### ISSUE TITLE
"Newer version of todo.txt in Dropbox" when that isn't the case.

### ISSUE THREAD

**Issue by 1minus1** [todotxt/todo.txt-ios#144]
When I open the app (working online), I can see it pull the newest file from my Dropbox, and the most recent edits I made on my computer show up fine. If I make any changes to items on iOS app, it tries to sync and says that there is a newer version of the file in my Dropbox. If I tap "Upload Changes", the file is uploaded (I can see it change on my computer) but the error box pops up again and says there is a newer version on Dropbox. This happens as many times as I hit "Upload Changes". If I hit "Download to Device", the changes I made on the device are saved to Dropbox and sync to my other computer fine. 

It seems like it uploads the updated file, then sees it as being newer than the version on the phone.

**Comment by 1minus1** [comment]
Seems similar to the issue described here, perhaps: http://forums.dropbox.com/topic.php?id=39833

**Comment by 1minus1** [comment]
I am shooting in the dark, but here's another link: http://forums.dropbox.com/topic.php?id=22347

**Comment by ginatrapani** [comment]
Is this the case problem that was resolved in version 1.0.1? More info:

http://tech.groups.yahoo.com/group/todotxt/message/4454

If not, get in touch on the mailing list so the community can help troubleshoot.
