### ISSUE TITLE
Accomodate iPhone5 4" retina screen

### ISSUE THREAD

**Issue by cbgrey** [todotxt/todo.txt-ios#148]
Release of the iPhone 5 prompts for support for a 4" retina layout.

**Comment by ginatrapani** [comment]
What are we missing?

**Comment by cbgrey** [comment]
It'll just need a retina sized launch image and each view will have to be configured to adjust to 3.5 or 4" screens.

**Comment by cbgrey** [comment]
I should add that it runs fine on an iPhone5 now but in "letterboxed' mode. No biggie but it would be nice to use the full screen size when available.

**Comment by cbgrey** [comment]
This issue was created in error. Apparently I was looking at an old branch of code. Looks good in 4" splendor.

**Comment by ginatrapani** [comment]
Ah good, glad to hear it. Thanks.
