### ISSUE TITLE
File Conflict

### ISSUE THREAD

**Issue by ghost** [todotxt/todo.txt-ios#158]
I get an "File Conflict" error if the "File Location" setting does not match exactly the dropbox folder (used upper instead of lower case) But the changes seems to be applied correctly.
After correcting the "File Location" setting everything is working fine.

I found the same issue in the mailinglist which seems to be already fixed in the android version.

This happens with the latest iOS version on iPad and iPhone.

**Comment by niklasfrykholm** [comment]
I had a similar problem. By default the synchronization path inside the iPhone app was set to "/todo". With this setting I got multiple conflict messages whenever changing _anything_ inside the App. I changed the synchronization path to "/todo.txt" and this fixed the problem.
