### ISSUE TITLE
Make 'completion date' optional

### ISSUE THREAD

**Issue by filblue** [todotxt/todo.txt-ios#159]
Hey, could anyone please explain why the 'completion date' is required for completed tasks? I believe this is too restrictive.

**Comment by ginatrapani** [comment]
Hi there -- Best place for discussion is the mailing list:

http://tech.groups.yahoo.com/group/todotxt/

On Mon, Jan 21, 2013 at 7:22 AM, filblue notifications@github.com wrote:

> Hey, could anyone please explain why the 'completion date' is required for
> completed tasks? I believe this is too restrictive.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ginatrapani/todo.txt-touch-ios/issues/159.

## 

http://ginatrapani.org
