### ISSUE TITLE
Match todo list aesthetics to Android version

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#16]
The todo.txt list view should match Android more closely, as shown here:

http://todotxt.com/images/todotouch1.jpeg

To do that we need to:
- Align todo ID with first line of text
- Grey contexts and projects
- Align priority w/ first line of text (DONE)
- Strikethrough completed tasks (DONE)

**Comment by rhussmann** [comment]
I'll claim this one. Priority should already be aligned with with first line of task text in the current master branch. I have a branch with strikethrough working (mostly... you can nitpick the strikethrough alignment, but it's 95% there). The strikethrough required writing a custom label that supports NSAttributedStrings. This means that this sort of label already supports multicolored text for display, we just need to setup the NSAttributedString properly.

I'm waiting for Gina to accept or reject my previous pull request that fixes cell display on the iPad. Once that's accepted I'll re-sync my master and merge into my dev branch. That will make the merge a lot easier for me.

**Comment by ginatrapani** [comment]
Fantastic, thanks! Just merged the iPad cell display pull.

On Sat, Oct 22, 2011 at 3:49 PM, Ricky
reply@reply.github.com
wrote:

> I'll claim this one. Priority should already be aligned with with first line of task text in the current master branch. I have a branch with strikethrough working (mostly... you can nitpick the strikethrough alignment, but it's 95% there). The strikethrough required writing a custom label that supports NSAttributedStrings. This means that this sort of label already supports multicolored text for display, we just need to setup the NSAttributedString properly.
> 
> I'm waiting for Gina to accept or reject my previous pull request that fixes cell display on the iPad. Once that's accepted I'll re-sync my master and merge into my dev branch. That will make the merge a lot easier for me.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/16#issuecomment-2493092

## 

http://ginatrapani.org
http://twitter.com/ginatrapani

**Comment by ginatrapani** [comment]
Great--just merged the strikethrough patch. Looks awesome.

I added one more thing to the Android aesthetics matching bit--the todo ID also should vertically align with the priority and first line of todo text. We're getting close!
