### ISSUE TITLE
Failed Sync caused data loss days later when synced

### ISSUE THREAD

**Issue by iamjonesdesigns** [todotxt/todo.txt-ios#160]
I know the topic isnt quite as clear as the problem actually is.  I used my tablet to acquire e-mail addresses at an event I worked.  I had planned to take the todo.txt file and copy all the addresses from it.  I didnt have wifi in the area I was working (unknowingly).  I checked the todo.txt from another machine and noticed it hadnt updated, so I opened up the tablet where I had been collecting e-mails and it was all erased.  

Is there anything I can do???

**Comment by ginatrapani** [comment]
Did you see a "File conflict: Upload or download from Dropbox" prompt? That's what the app does when changes have been made offline and then it comes back online.

**Comment by iamjonesdesigns** [comment]
I did not get the file conflict.
