### ISSUE TITLE
Integrate Dropbox sync API?

### ISSUE THREAD

**Issue by rhussmann** [todotxt/todo.txt-ios#162]
Looks like Dropbox has release a new sync API. I haven't investigated it at all, but would this be a good fit for todo.txt-touch (both Android and iOS)?

https://www.dropbox.com/developers/sync

**Comment by ginatrapani** [comment]
Hi Ricky! We investigated SyncAPI, and it's not a good fit https://github.com/ginatrapani/todo.txt-touch/issues/317
