### ISSUE TITLE
Enable todo filters

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#18]
Should be able to sort todo's by project, context, and/or keyword, as you can in the Android version.

**Comment by chuckbjones** [comment]
I'm going to start on this one. At least the search bar portion.

**Comment by chuckbjones** [comment]
Search bar is implemented and pull request has been made. I don't know when I'll have a chance to do more, so someone else can feel free to look at filtering.

**Comment by ginatrapani** [comment]
@bigbash Are you working on the filter project/context picker? Now that search is implemented, that's the last big missing piece of functionality.

**Comment by mcguiresm** [comment]
@ginatrapani I'm going to look into it night, I may need some help though.  @jperkel feel like tackling this with me?

**Comment by jperkel** [comment]
@bigbash, @ginatrapani, @chuckbjones sorry for the delayed reply, I've been on vacation. I can try to help out on this, but not sure where to start. @bigbash, how about if we chat further one on one, ie not in this thread?

thx! -- jp

**Comment by mcguiresm** [comment]
@jperkel If you want we can chat in #todotxtapp on IRC.

**Comment by anka-213** [comment]
How is the sorting progressing? If no one is working on it I'll probably try doing it myself.

**Comment by ginatrapani** [comment]
As far as I know, no one's actively working on this at the moment. The first thing we have to do is figure out what the UI should look like. Here's the mailing list thread where the community can discuss:

http://tech.groups.yahoo.com/group/todotxt/message/4624

**Comment by ginatrapani** [comment]
Merged in 55061294f028c48bfe6a5545fcb74aba8bb373de
