### ISSUE TITLE
Bittorrent Sync

### ISSUE THREAD

**Issue by medoni** [todotxt/todo.txt-ios#182]
Are any plans to use bittorrent sync instead of dropbox?

**Comment by ginatrapani** [comment]
No, sorry.

**Comment by hejsan** [comment]
Hi, sorry for the resurrection, but to "support" bittorrent-sync all that is needed is to allow user to select folder that is not synced by dropbox, and then not attempt to sync it via dropbox.
Any chance you'd consider that?
Thanks.

**Comment by mbaldw1n** [comment]
I wanted to resurrect this again as I am looking for a solution that doesn't use Dropbox for IOS, and this would be great.  Any chance you could let us know if you would consider making the change suggested above?

**Comment by ginatrapani** [comment]
Here's more info: http://blog.todotxt.com/post/83519225401/faq-support-for-cloud-providers-other-than-dropbox
