### ISSUE TITLE
Latest ToDoTXT update is crashing iPhone 5 on iOS 6.1.4

### ISSUE THREAD

**Issue by stevethinkdata** [todotxt/todo.txt-ios#184]
I installed the latest ToDoTXT update and it crashes now virtually every time I open the app.  I've used it for a while so this is problematic - is there any way to revert to an older version of the app on iTunes?  Is anyone else experiencing the same issues?

**Comment by ginatrapani** [comment]
If you uninstall and reinstall, does that help?

**Comment by stevethinkdata** [comment]
Uninstall and reinstall does seem to help – one other item to note though – when I change priority for a task it doesn’t update immediately like in the older version.  Perhaps that’s a known issue…  thanks for the prompt response!

**Comment by ginatrapani** [comment]
Glad to hear that helped. Confirmed prioritization bug, filed ticket #186.

Thanks.

**Comment by stevethinkdata** [comment]
FYI after installing iOS 7 on my iPhone 5 it appears that editing a task causes the text to disappear or move so far up that you cannot see it and adding a task does the same.  I tried uninstalling / reinstalling again too.  Let me know if you want screenshots sent and I’ll supply them
