### ISSUE TITLE
Back to list button hides top task

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#185]
In iOS 7, tap on a task to view Task Details. Then tap the <  Todo.txt button to go back to list view. The list is slightly scrolled down, with the first task hidden under the top bar.

At the very least, going back to the task list should position you at the top of the list, with the highest task displayed.

Even better, going back to the task list will return you to the exact position of the task whose details you were viewing.

UPDATE: What I think is the same issue:

Tap a task, and tap "Update." Make changes, and tap "Save." Back at the Task Details view, the page is slightly scrolled up, under the top bar.

**Comment by dmd** [comment]
This is still an issue in the new version released today.

**Comment by ginatrapani** [comment]
Yep. This isn't fixed yet. We'll close the ticket when it is.
