### ISSUE TITLE
ios7 deleting task doesn't work

### ISSUE THREAD

**Issue by dmd** [todotxt/todo.txt-ios#188]
Deleting a task doesn't work - or least doesn't show up - on ios7.

Tap a task, tap delete. Tap 'delete task'. 

Expected behavior: it goes back to the list page, with task deleted.

Observed behavior: it goes back to Task Details.

**Comment by portenkirchner** [comment]
Experiencing the same behavior on a iPhone 4. Deleting the task still shows this task and the task details, but when I tap Todo.txt to go back to the list, the deleted task is not showing up in the list anymore.
