### ISSUE TITLE
crash on launch. 

### ISSUE THREAD

**Issue by dmd** [todotxt/todo.txt-ios#192]
Now I'm getting crash on launch every time, even after hard reset of phone.

Crash log: http://ix.io/8ej

**Comment by ginatrapani** [comment]
Is this on iPhone 5 with iOS 7?
How many lines is your todo.txt file?
Did you try uninstalling the app and reinstalling?

**Comment by dmd** [comment]
Yes, as the crash log says:
Hardware Model:      iPhone5,2
OS Version:          iOS 7.0 (11A465)

Todo.txt is currently 4 lines.

Reinstalling lets me launch without crashing again.

**Comment by shubaly** [comment]
Todo.txt has also been crashing for me since a recent update.

iPhone 4.1
Version 1.6
OS Version: iOS 7.0 (11A465)

**Comment by chuckbjones** [comment]
I'm able to crash the app in the simulator and should have a fix this week. I don't know if it's the same issue that everyone else is seeing, though.
