### ISSUE TITLE
display of age of tasks is incorrect across month boundaries

### ISSUE THREAD

**Issue by dmd** [todotxt/todo.txt-ios#195]
If I create a task on, say, September 30, then on October 1 todotxt will display it as '1 month ago'.

Expected behavior would be 'yesterday' or '1 day ago'.

**Comment by chuckbjones** [comment]
I believe this logic was originally ported from the buggy implementation in the Android app. I fixed the Android code in [this commit](https://github.com/ginatrapani/todo.txt-android/commit/9fdfc0cca864a70bdb25301e798987744d554485). The same change probably needs to be made here.
