### ISSUE TITLE
Increase task font size on individual task screen

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#20]
The todo item font size looks awfully small on the individual task view. It should at least match the font size of the button items.

**Comment by ginatrapani** [comment]
Done! https://github.com/ginatrapani/todo.txt-touch-ios/commit/0d4dd6dbee7e6c86ecef68172899c39fa750ff35

**Comment by ginatrapani** [comment]
Actually: the task text on the individual task screen still has to be enlarged. Reopening the issue.

**Comment by rhussmann** [comment]
What's the desired functionality here? When on this screen, do we want the text styling to match what is shown in the overall view? For instance, do we want completed items to have strikethrough?

**Comment by ginatrapani** [comment]
Yes, exactly. Should match the list view.

Sent from my mobile
On Oct 23, 2011 9:16 AM, "Ricky" <
reply@reply.github.com>
wrote:
