### ISSUE TITLE
ActionSheetPicker errors in console

### ISSUE THREAD

**Issue by chuckbjones** [todotxt/todo.txt-ios#210]
Getting the following error in the console log in the simulator when opening any ActionSheetPicker like the project or context pickers.

> <Error>: CGContextRestoreGState: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by stevendpclark** [comment]
This should be fixed now with Chuck's pull request https://github.com/ginatrapani/todo.txt-ios/pull/231. Can we close this? I'm not seeing these errors anymore

**Comment by ginatrapani** [comment]
Yep, closing. thanks!
