### ISSUE TITLE
Privacy issue of DropBox for iOS and Androïd TODOTXT apps

### ISSUE THREAD

**Issue by mdan312** [todotxt/todo.txt-ios#218]
Snowden has proved that every file put on DropBox is intercepeted and archived by NSA and possibly others.
What about supporting a simple private WebDAV ? It would be more open (OwnCloud, etc..)

**Comment by mdan312** [comment]
I do not want every single todo task I plan to be read by people who do not have to go into others' business

**Comment by ginatrapani** [comment]
Here's how to work offline and never sync to Dropbox: http://blog.todotxt.com/post/83519225401/faq-support-for-cloud-providers-other-than-dropbox
