### ISSUE TITLE
Add Compose Todo "Hint" text

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#22]
The Android version offers some "Hint" text in the compose todo box. Is this possible in iOS? Our current Android compose text is an example todo:

Call Mom @Phone +FamilialPeace

This is what it looks like:

![Add task](https://img.skitch.com/20111027-t8a1usb2qrm4ha9reyiim3ibja.png)

**Comment by mcguiresm** [comment]
Mine!

**Comment by chuckbjones** [comment]
This looks promising: http://stackoverflow.com/questions/1328638/placeholder-in-uitextview/3516201#3516201

@bigbash, are you still planning on working on this one? If not, I'll try to take care of it.

**Comment by mcguiresm** [comment]
@chuckbjones sorry for the delayed response, I have time set aside this week to work on this one as well as looking at some of the other issues.

**Comment by ginatrapani** [comment]
Hi @bigbash, just checking in--where are you with this one? Looks like @chuckbjones will have some time to work on the app this coming week and might even have done some work on this. Okay if he goes ahead with a pull request, or do you have something in progress? No pressure, just want to see where we are.

**Comment by mcguiresm** [comment]
Hey @ginatrapani, unfortunately I haven't been able to work on it, if @chuckbjones wants to he can do it, it'll probably take him a lot less time than it would take me.  I'll just learn from what he does.  Sorry that I haven't been able to do this.

**Comment by ginatrapani** [comment]
No problem Shawn, thanks for getting back. I completely understand
being busy. :)

On Thu, Dec 1, 2011 at 8:58 AM, Shawn McGuire
reply@reply.github.com
wrote:

> Hey @ginatrapani, unfortunately I haven't been able to work on it, if @chuckbjones wants to he can do it, it'll probably take him a lot less time than it would take me.  I'll just learn from what he does.  Sorry that I haven't been able to do this.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ginatrapani/todo.txt-touch-ios/issues/22#issuecomment-2977147

## 

http://ginatrapani.org
http://twitter.com/ginatrapani
