### ISSUE TITLE
iPad: Sort picker screen placement is way off

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#23]
It shows up near the top left of the screen, should appear above the button. Also, it could be taller since the iPad offers more screen real estate.

**Comment by raykrash** [comment]
This seems to happen because the keyboard + buttons disappears when the picker appears.  There is no location to anchor the picker.  
Since iPad has ample space, perhaps we should not hide the keyboard.

I will work on this.

**Comment by raykrash** [comment]
I fixed this issue and created a pull request.

**Comment by ginatrapani** [comment]
Thank you! I'll review these this weekend. Appreciate it.

Sent from my mobile
On Oct 28, 2011 1:34 AM, "ramkola" <
reply@reply.github.com>
wrote:
