### ISSUE TITLE
Priority/Context action sheets no longer display items within iOS 8

### ISSUE THREAD

**Issue by stevendpclark** [todotxt/todo.txt-ios#230]
After upgrading to iOS 8, the Priority/Context action sheet pickers fail to work within the edit task screen, nor does the sort action sheet picker work on the main screen. 

![ios simulator screen shot sep 24 2014 11 24 35 pm](https://cloud.githubusercontent.com/assets/3989899/4399176/d6aa8444-4463-11e4-9256-10e4d93312f2.png)

I believe this problem is due to the iOS todo.txt project using an older version of the [ActionSheetPicker](https://github.com/TimCinel/ActionSheetPicker) project. It will need to be updated to use the [new forked version](https://github.com/skywinder/ActionSheetPicker-3.0).

**Comment by kud1ing** [comment]
I have this too.

**Comment by sukima** [comment]
Same here. Any one got any ideas on what might be the cause? Or perhaps seen something similar in other apps?

**Comment by ginatrapani** [comment]
Anyone available to try to upgrade ActionSheetPicker? My first try failed with many build errors.

**Comment by chuckbjones** [comment]
I've got it almost figured out. A lot of the API changed.

**Comment by chuckbjones** [comment]
Sent a PR. Only tested on simulators (iPhone 5s and iPad Air). Couldn't figure out how to run unit tests. It looks like the framework we were using is no longer supported?

**Comment by ginatrapani** [comment]
Thanks again Chuck! re: testing framework, I upgraded us from OCUnit to XCTest in 
https://github.com/ginatrapani/todo.txt-ios/commit/13f8cb283077cc2b8e3d5ccd56efd4f392e4acf4

We have some "issues" in the StringsTest but I think they're just a syntax issue.

**Comment by stevendpclark** [comment]
Thanks Chuck for fixing the issue, just didn't have time to get around to it. 

I have created a pull request to fix the issues running the unit tests within https://github.com/ginatrapani/todo.txt-ios/pull/232

**Comment by sukima** [comment]
I've tested the merge on iOS 8.0 (iPhone 5s) and it works. :heavy_check_mark:
