### ISSUE TITLE
Cannot find todo.txt in iTunes Store 

### ISSUE THREAD

**Issue by leira** [todotxt/todo.txt-ios#248]
I followed the link on todotxt.com, it shows no app in iTunes Store. I tried to search todo.txt in iTunes Store, can't find any thing really relate to todo.txt either. I'm using US store. Has it been pulled out for some reason?

**Comment by ginatrapani** [comment]
Apologies; I was late to agree to Apple's updated terms. I went ahead and did so and the app has been restored to the store.

**Comment by tmitchell** [comment]
Tried looking for this on the iTunes Store today and got:

### Item Not Available

The item you've requested is not currently available in the U.S. store.
