### ISSUE TITLE
Dropbox limited access

### ISSUE THREAD

**Issue by alimoeeny** [todotxt/todo.txt-ios#249]
Are there any plans to ask for a more limited access to dropbox? like just for an app data directory access. Not to the whole dropbox? I noticed the app in the app store (which I assume is the same code base) asks for access to the entirety of dropbox.

**Comment by ginatrapani** [comment]
To preserve interoperability with other text editors and Todo.txt clients, we decided to keep it full-access. Here's the thread where the community discussed this:

https://groups.yahoo.com/neo/groups/todotxt/conversations/topics/4802
