### ISSUE TITLE
iPad: Don't prematurely wrap long task text

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#25]
Right now a lengthy todo wraps too soon inside the cell on the iPad. It should fill the cell all the way to the right.

**Comment by rhussmann** [comment]
I'm working on this.

**Comment by ginatrapani** [comment]
Task text is no longer truncated thanks to this commit:

https://github.com/ginatrapani/todo.txt-touch-ios/commit/0d4dd6dbee7e6c86ecef68172899c39fa750ff35

But on the iPad it still wraps prematurely, so going to leave this issue open and reword the title to say the task text should horizontally fill the cell on the iPad. Thanks again Ricky.

**Comment by rhussmann** [comment]
That's my fault, I never built/tested for iPad. The code is currently only considering hard-coded cell-widths for iPhone. I'd like to claim the fix for the iPad. A note for the future: I think we can do some really cool stuff with a split-view layout designed specifically for the iPad, or at least not be constrained to mirroring the iPhone layout. Might be something to consider for 2.0.

**Comment by ginatrapani** [comment]
> A note for the future: I think we can do some really cool stuff with a split-view layout designed specifically for the iPad, or at least not be constrained to mirroring the iPhone layout. Might be something to consider for 2.0.

I agree! I've been thinking about a split view where a list of projects and/or contexts is in the left column, and when you tap you see the list of tasks associated with them. Definitely on the 2.0 list.

**Comment by chuckbjones** [comment]
> I've been thinking about a split view where a list of projects and/or contexts is in the left column, and when you tap you see the list of tasks associated with them.

That sounds awesome! We definitely need to take advantage of the larger screen on the iPad. We should also keep in mind landscape vs portrait orientations.
