### ISSUE TITLE
Remove Dropbox requirement, or make the dependency explicit

### ISSUE THREAD

**Issue by jish** [todotxt/todo.txt-ios#250]
I'm using the todo.txt CLI and I like it, so I decided to support the open source effort. I purchased the iOS app only to find out it requires a Dropbox account. Yes, in hindsight if I read the app description carefully it states that a Dropbox account is required, but I managed to overlook that before purchasing :(

I would personally prefer to use the app without giving my personal information to Dropbox, but if Dropbox support has to be required, then it would be nice if the marketing site http://todotxt.com/ made this more clear. Also, since the first thing you see in the app is a giant log into Dropbox button, maybe consider moving the "Dropbox is required" part to the first line of the app store description.

In an effort to make this critique not entirely negative, thanks for making the todo.txt CLI! :smiley: I still use that and like its simplicity.

**Comment by ginatrapani** [comment]
Sorry the Dropbox requirement wasn't clear. Email me if you'd like a refund; would be happy to send it.

Here's a workaround (in short, use a dummy Dropbox account & turn off syncing).

http://blog.todotxt.com/post/83519225401/faq-support-for-cloud-providers-other-than
