### ISSUE TITLE
Long-text cells display incorrectly when searching

### ISSUE THREAD

**Issue by rhussmann** [todotxt/todo.txt-ios#32]
## Summary

Tasks with long text display fine in the normal view, but if searching from the tableview for a task with long text, it won't display correctly in the search view.
## Expected behavior

In a search view, task should display in a cell of appropriate height to house all text
## Actual behavior

The tasks cell is too short to handle properly display the text.
## Steps to reproduce (iPhone):
1. Create a task with a lot of text, for instance, e.g. "This is a very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very very long task"
2. Pull down the tableview to reveal the search bar. Search for text in the task, e.g. "very"
3. The resulting task cell won't be tall enough to fit the long text.
## Image of Bug

http://cl.ly/B4mY
## Notes

If it doesn't step on Chuck's work too much, I'd like to claim this one. Should be a quick fix.

**Comment by ginatrapani** [comment]
Acknowledged, thanks! All yours.
