### ISSUE TITLE
"Add task" screen should using texting keyboard

### ISSUE THREAD

**Issue by rhussmann** [todotxt/todo.txt-ios#41]
# Summary

The "add task" screen should use the standard texting keyboard to facilitate faster text entry.
# Discussion

I understand that the current keyboard provides somewhat faster access to characters designating context and project (@ and +, respectively). However, the majority of my time is spent entering task text, not the attribute characters. I find myself consistently frustrated when adding TODOs, fighting the muscle memory I've developed with the standard keyboard. As this is a workflow I frequently perform (adding new tasks), it should fit the standard keyboard model.

In addition, the button in the upper right-hand corner should read "Add," not "Done," as done has special meaning within the context of todo.txt Touch.

I'll happily claim this one if we agree this bug is valid.
# Supporting images
- [Current keyboard](http://dl.dropbox.com/u/30962/Photo%20Oct%2024%2C%2012%2059%2044%20PM.png)
- [Desired keyboard](http://dl.dropbox.com/u/30962/Photo%20Oct%2024%2C%201%2001%2050%20PM.png)

**Comment by mcguiresm** [comment]
Just on a quick test if you add <code>textView.keyboardType = UIKeyboardTypeDefault;</code> after <code>textView.inputAccessoryView = accessoryView;</code> in [TaskEditViewController.m](https://github.com/ginatrapani/todo.txt-touch-ios/blob/master/Classes/TaskEditViewController.m#L165) that will change the keyboard to the desired one.

**Comment by rhussmann** [comment]
Fair enough, just wanted to make sure this was okay, as a group, before making a move on it.

**Comment by mcguiresm** [comment]
There was feedback on there being no ":" that would be used for due dates or times with the current keyboard layout.
