### ISSUE TITLE
Add support for 4.2.1 iOS

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#53]
One of our TestFlight testers is running iOS 4.2.1, might as well compile for it.

**Comment by flafeer** [comment]
Is the goal to support iPhone 3G and 2nd gen iPod Touch? If so, you might want to explicitly add armv6 to the supported architectures. That is no longer in the standard list as of Xcode 4.2.

(I think most people running 4.2.1 still are probably on iPhone 3G or the 2nd gen iPod)
