### ISSUE TITLE
Upgrade Dropbox SDK to iOS v1.0

### ISSUE THREAD

**Issue by rhussmann** [todotxt/todo.txt-ios#56]
# Summary

Currently, Todo.txt Touch iOS uses an older version of the Dropbox API. While this works fine for developers who have created an API key before the 1.0 SDK was released, new developers who create an API key and attempt to use it with Todo.txt touch iOS will receive the message "Unable to Login -- You're using an older version of the Dropbox API with a new API key. Please use the latest version" when attempting to link their Dropbox account.

As a consequence, no developers requesting an API key after the release of Dropbox v1.0 iOS SDK (which has already occurred) will be able to interact with Dropbox within Xcode. In other words, new developers can't effectively build Todo.txt touch iOS.
# Steps to reproduce

1.) Request a new API key from the Dropbox website.
2.) Use these keys in the dropbox.plist file of Todo.txt touch iOS
3.) Receive the previously mentioned message, a.k.a. fail miserably
# Suggested fix

Upgrade Dropbox SDK to iOS v1.0.

**Comment by chuckbjones** [comment]
I'll take a stab at this one.
