### ISSUE TITLE
iPad split-view layout

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#81]
![Page 1](https://github.com/ginatrapani/todo.txt-cli/raw/gh-pages/images/Todo.txt%20Touch%20for%20iPad%20-%20Page%201.png)

![Page 2](https://github.com/ginatrapani/todo.txt-cli/raw/gh-pages/images/Todo.txt%20Touch%20for%20iPad%20-%20Page%202.png)

**Comment by mcguiresm** [comment]
Looks nice, I assume the left side is to toggle the filtering?

**Comment by ginatrapani** [comment]
Merged in 55061294f028c48bfe6a5545fcb74aba8bb373de
