### ISSUE TITLE
Remove TestFlight hooks/Add About button before app submission

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-ios#85]
Hoping to submit the app to the store for approval in the next two weeks. Before we do, we have to remove all the TestFlight hooks, including the Leave Feedback button in Settings.  I'd like to replace it with an "About Todo.txt Touch" that just launches todotxt.com in mobile Safari. (I'm working on a web site redesign right now).

**Comment by ginatrapani** [comment]
@bigbash, can you help with this one?

**Comment by mcguiresm** [comment]
@ginatrapani I'll remove the TestFlight hooks/references and change the Leave feedback to "About Todo.txt Touch" when I get home, around 6PM CST

**Comment by ginatrapani** [comment]
Fantastic, thanks!
