### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by chuckbjones** [todotxt/todo.txt-ios#90]
The app icon we are using is from the Android app, I believe, and it deviates slightly from the Apple guidelines:
http://developer.apple.com/library/ios/#documentation/userexperience/conceptual/mobilehig/IconsImages/IconsImages.html

Also, the large image shown on the login screen is pixelated on retina devices (at least in the simulator) can we get a higher resolution one?

**Comment by ginatrapani** [comment]
Ah yes, asking our designer about this now.
