### ISSUE TITLE
Remove Task Details screen

### ISSUE THREAD

**Issue by chuckbjones** [todotxt/todo.txt-ios#96]
I would like to merge the functionality of the individual task screen into the main list screen. Then we could remove that screen entirely.

**Comment by ginatrapani** [comment]
Agreed we should do this. You should be able to perform actions on a task without tapping through to a task details screen.

Ideally it would work the way Android does: select a task and a contextual action menu becomes available. Select multiple tasks, same deal.

**Comment by ginatrapani** [comment]
Superseded by #172
